### ISSUE TITLE
We need '/flute list-fingeprint' command

### ISSUE THREAD

**Issue by asn-d6** [asn-the-goblin-slayer/flute#11]
We need a command that prints the current public key fingerprint, so that it's possible to pass it to others off-band (so that they can trust it with trust-key).

Currently the only possible way to pass public keys to friends are through the stupid '/flute introduction' command.

**Comment by Mandragorian** [comment]
I made a PR  ( #12 ) that probably adds this functionality

**Comment by asn-d6** [comment]
Thanks! Merged the PR. Closing this issue.

Onwards!
