### ISSUE TITLE
/viola introduction with no nick should use current nick's buffer

### ISSUE THREAD

**Issue by fauno** [asn-the-goblin-slayer/flute#4]
when i ran `/viola introduction` on a private conversation i got a list index out of range error.  i would expect to use the current nick, like `/otr start`

**Comment by asn-d6** [comment]
Thanks for the suggestion. This is a UX feature that I have also been considering.

I was about to write some instructions on implementing this feature in case you wanted to write a patch, but after all I ended up doing it myself.

You can find the patch here: https://github.com/asn-the-goblin-slayer/viola/commit/c2f1cd6a6760a109a12652284dc9dcef7628b495

Please test it by pulling latest master. Let me know if it works well :)
