### ISSUE TITLE
can't rejoin channel

### ISSUE THREAD

**Issue by fauno** [asn-the-goblin-slayer/flute#8]
sometime in the history of #viola_test i ended up with an old room key, so everytime someone says something i just get 

```
19:14:42              [Viola] Could not decrypt message sent in room. Maybe old key. Try rejoining the channel.
```

but `/viola join-room` just tells me 

```
19:11:59              [Viola] Channel #viola_test is already a viola room
```

and there's no command to disable encryption, `/part` and `/join` won't do either :P

**Comment by asn-d6** [comment]
Yes, indeed. Viola has no logic currently to rejoin an already active room. Sucks.
This has been already filed as https://github.com/asn-the-goblin-slayer/viola/issues/3 .

It shouldn't be too hard to fix, if someone wants to try to patch it. I have provided some info on how to fix it at https://github.com/asn-the-goblin-slayer/viola/issues/3 . Let me know if you need more info.

Closing this one.
